fixed first test in localStorage to pass

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -23,4 +23,4 @@ jobs:
 
       - name: Jest
         id: jest
-        run: npx jest || echo '::set-output name=status::failure'
+        run: jest || echo '::set-output name=status::failure'
